"""Application configuration utilities."""

from functools import lru_cache
from pathlib import Path
from typing import Optional

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Configuration values loaded from environment variables."""

    logfire_api_key: Optional[str] = Field(
        default=None,
        alias="LOGFIRE_API_KEY",
        description="Logfire API key for centralized logging.",
    )
    logfire_project: Optional[str] = Field(
        default=None,
        alias="LOGFIRE_PROJECT",
        description="Logfire project identifier in the form 'user/project-name'.",
    )
    chroma_path: Path = Field(
        default=Path("chroma_db"),
        description="Filesystem path for the persistent ChromaDB store.",
    )
    data_pages_dir: Path = Field(
        default=Path("data_pages"),
        description="Directory where raw catalog page HTML dumps are stored.",
    )
    data_csv_path: Path = Field(
        default=Path("data") / "shl_individual_assessments.csv",
        description="Path to the catalog CSV generated by the crawler.",
    )
    data_json_path: Path = Field(
        default=Path("data") / "shl_individual_assessments.json",
        description="Path to the catalog JSON generated by the crawler.",
    )
    embeddings_model_name: str = Field(
        default="sentence-transformers/all-MiniLM-L6-v2",
        description="SentenceTransformers model used for embedding generation.",
    )
    collection_name: str = Field(
        default="shl_assessments",
        description="Chroma collection name for assessment embeddings.",
    )
    candidate_pool_size: int = Field(
        default=20,
        description="Number of candidates to retrieve from the vector store before ranking.",
    )
    recommendation_limit: int = Field(
        default=10,
        description="Maximum number of assessments returned to clients.",
    )
    min_category_mix: int = Field(
        default=3,
        description="Minimum number of assessments per category when a balanced mix is required.",
    )
    gemini_api_key: Optional[str] = Field(
        default=None,
        alias="GEMINI_API_KEY",
        description="Gemini API key for LLM-based type extraction.",
    )

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return the cached settings instance."""

    return Settings()

